name: Scrape IGN Game List

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # every day at 6am UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install beautifulsoup4 requests

      - name: Run scraper
        run: python scrape_games.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ `git status --porcelain` ]]; then
            git add games.json
            git commit -m "Update games.json from IGN scrape"
            git push
          else
            echo "No changes to commit."
          fi
